<wsdl:definitions
     name="MergeCustDetails"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OnlineBatch25/MergeDetails/MergeCustDetails"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OnlineBatch25/MergeDetails/MergeCustDetails"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/MergeCustDetails"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="MergeCustDetails_plt" >
    <plt:role name="MergeCustDetails_role" >
      <plt:portType name="tns:MergeCustDetails_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/MergeCustDetails" schemaLocation="../Schemas/MergeCustDetails_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="CustomerCollection_msg">
        <wsdl:part name="CustomerCollection" element="top:CustomerCollection"/>
    </wsdl:message>
    <wsdl:portType name="MergeCustDetails_ptt">
        <wsdl:operation name="merge">
            <wsdl:input message="tns:CustomerCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
